### ISSUE TITLE
Consensus set hangs when closing

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/rivine#543]
a running daemon closed with Ctrc-C hangs indefinitely. Sometimes it also corrupts the consensus DB if you `pkill` it

**Comment by LeeSmet** [comment]
Output when starting again:

```
Loading...
Binding API Address and serving the API...
Loading gateway (0/5)...
Loading consensus set (1/5)...
Closing consensus set...
Context is done, quitting...
context is done, quitting...
```

**Comment by robvanmieghem** [comment]
@LeeSmet was it started with "no-bootstrap"?
If so, commit 43c5a47489e1ce58fbbbd99877342a126abf4cb7 might solve this

**Comment by LeeSmet** [comment]
@robvanmieghem  yes, though it did not get as far since it hangs on the consensus and it will only close the gateway after that. So that would be another problem.

**Comment by robvanmieghem** [comment]
```
goroutine 23 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0xc00032c178)
        /usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc00032c170)
        /usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/consensus.(*ConsensusSet).initPersist.func2()
        /Users/rob/workspace/go/src/github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/consensus/persist.go:88 +0x3c
github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/sync.(*ThreadGroup).Stop(0xc00032c200, 0x0, 0x0)
        /Users/rob/workspace/go/src/github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/sync/threadgroup.go:146 +0x158
github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/consensus.(*ConsensusSet).Close(0xc00032c000, 0x1, 0x1)
        /Users/rob/workspace/go/src/github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/consensus/consensusset.go:342 +0x33
main.runDaemon.func3.2(0x16b3600, 0xc00032c000)
        /Users/rob/workspace/go/src/github.com/nbh-digital/goldchain/cmd/goldchaind/daemon.go:126 +0x75
main.runDaemon.func3(0xc0000971e0, 0xc00025a1c0, 0xc0000a6b40, 0xc00025e220, 0xc0000b4560, 0x5, 0x5, 0xc0000aacc0, 0x16ad060, 0xc000098840, ...)
        /Users/rob/workspace/go/src/github.com/nbh-digital/goldchain/cmd/goldchaind/daemon.go:293 +0x9d3
created by main.runDaemon
        /Users/rob/workspace/go/src/github.com/nbh-digital/goldchain/cmd/goldchaind/daemon.go:65 +0x37b
```
being on 
```cs.tg.AfterStop(func() {
		cs.pluginsWaitGroup.Wait()
		err := cs.db.Close()
		if err != nil {
			cs.log.Println("ERROR: Unable to close consensus set database at shutdown:", err)
		}
	})
```
the `cs.pluginsWaitGroup.Wait()`

**Comment by robvanmieghem** [comment]
problem is that  PluginViewStorage is never closed apparently
```

// Close closes pluginViewStorage
func (ps *PluginViewStorage) Close() error {
	ps.wg.Done()
	return nil
}

**Comment by robvanmieghem** [comment]
It works the first time the daemon is ran, the second time, it fails again, some extra logging indicates there are no registered plugins on the consensus closing while the registerplugin gives no error

**Comment by robvanmieghem** [comment]
after adding debuglogging in Rivine, this shows up in the logs:
```

2019/07/09 10:25:43.801536 plugin.go:55: [DEBUG] Registering plugin  authcointx
2019/07/09 10:25:43.801640 plugin.go:275: [DEBUG] Creating new pluginstorage for  authcointx
2019/07/09 10:25:43.802017 plugin.go:55: [DEBUG] Registering plugin  minting
2019/07/09 10:25:43.802059 plugin.go:275: [DEBUG] Creating new pluginstorage for  minting
2019/07/09 10:25:43.804598 consensusset.go:188: Bootstrap enabled, starting IBD
2019/07/09 10:25:51.305962 plugin.go:301: [DEBUG] Number of plugins to close: 0
```
No errors on the console though

**Comment by robvanmieghem** [comment]
ok, found it:
https://github.com/threefoldtech/rivine/blob/master/modules/consensus/plugin.go#L96
while the plugin is registered in the plugin map later:
https://github.com/threefoldtech/rivine/blob/master/modules/consensus/plugin.go#L121
