### ISSUE TITLE
travis fails with "No output has been received in the last 10m0s"

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/rivine#597]

**Comment by robvanmieghem** [comment]
Has been a while now, moving it out of the current project

**Comment by robvanmieghem** [comment]
reappearing consistently now

**Comment by robvanmieghem** [comment]
```

**Comment by robvanmieghem** [comment]
--- FAIL: TestHealthyNodeListPruning (90.88s)
    nodes_test.go:412: peers are not sharing nodes with eachother
```

**Comment by robvanmieghem** [comment]
well, not consistently: https://travis-ci.org/threefoldtech/rivine/builds/631780490

**Comment by robvanmieghem** [comment]
Removed the parallel code from the untittestcode since it is not about functionality and made it configurable

**Comment by robvanmieghem** [comment]
Still happening, might have to do with 2f1df088ab8f45b3aa14c53eadc882bb3b453056

**Comment by robvanmieghem** [comment]
Might also be 
```
=== RUN   TestThreadedHandleConn
goroutine 8421 [running]:
runtime/debug.Stack(0x12ad4f4, 0xc000374410, 0xc000d8aa38)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xab
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x34
github.com/threefoldtech/rivine/build.Critical(0xc000d8abf0, 0x1, 0x1)
	/Users/rob/workspace/go/src/github.com/threefoldtech/rivine/build/critical.go:15 +0xa4
github.com/threefoldtech/rivine/pkg/encoding/siabin.(*Decoder).decode(0xc00187fea0, 0x157f900, 0xc002b86d58, 0x191)
	/Users/rob/workspace/go/src/github.com/threefoldtech/rivine/pkg/encoding/siabin/marshal.go:328 +0x984
github.com/threefoldtech/rivine/pkg/encoding/siabin.(*Decoder).Decode(0xc00187fea0, 0x1573120, 0xc002b86d58, 0x0, 0x0)
	/Users/rob/workspace/go/src/github.com/threefoldtech/rivine/pkg/encoding/siabin/marshal.go:230 +0x163
github.com/threefoldtech/rivine/pkg/encoding/siabin.Unmarshal(0xc002b689b8, 0x3, 0x3, 0x1573120, 0xc002b86d58, 0x3, 0x0)
	/Users/rob/workspace/go/src/github.com/threefoldtech/rivine/pkg/encoding/siabin/marshal.go:357 +0x130
github.com/threefoldtech/rivine/pkg/encoding/siabin.ReadObject(0x5721ac0, 0xc0003d7900, 0x1573120, 0xc002b86d58, 0x8, 0x0, 0x1a45320)
	/Users/rob/workspace/go/src/github.com/threefoldtech/rivine/pkg/encoding/siabin/prefix.go:32 +0xd2
github.com/threefoldtech/rivine/modules/gateway.(*Gateway).threadedHandleConn(0xc00009c700, 0x16c07c0, 0xc0003d7900)
	/Users/rob/workspace/go/src/github.com/threefoldtech/rivine/modules/gateway/rpc.go:208 +0x244
github.com/threefoldtech/rivine/modules/gateway.(*Gateway).threadedListenPeer.func2(0xc001b963c0, 0xc00009c700, 0x16c07c0, 0xc0003d7900)
	/Users/rob/workspace/go/src/github.com/threefoldtech/rivine/modules/gateway/rpc.go:184 +0x81
created by github.com/threefoldtech/rivine/modules/gateway.(*Gateway).threadedListenPeer
	/Users/rob/workspace/go/src/github.com/threefoldtech/rivine/modules/gateway/rpc.go:181 +0x3e6
Critical error: unexpected EOF
``
And this holds the created  gateways in the test alive

**Comment by DylanVerstraete** [comment]
Might be in test `TestPruneNodeThreshold`, checking right now.

**Comment by robvanmieghem** [comment]
My previous assumption was wrong, even though it is completely wrong to panic, print such errormessages and recover in a plain decoder, this seems to be the culprit:
```
goroutine 8390 [semacquire, 14 minutes]:
sync.runtime_Semacquire(0xc00009c7b8)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc00009c7b0)
	/usr/local/go/src/sync/waitgroup.go:130 +0xb1
github.com/threefoldtech/rivine/sync.(*ThreadGroup).Stop(0xc00009c758, 0x0, 0x0)
	/Users/rob/workspace/go/src/github.com/threefoldtech/rivine/sync/threadgroup.go:140 +0x1c5
github.com/threefoldtech/rivine/modules/gateway.newGateway.func2()
	/Users/rob/workspace/go/src/github.com/threefoldtech/rivine/modules/gateway/gateway.go:234 +0x5a
github.com/threefoldtech/rivine/sync.(*ThreadGroup).Stop(0xc00009c7f0, 0x0, 0x0)
	/Users/rob/workspace/go/src/github.com/threefoldtech/rivine/sync/threadgroup.go:135 +0x134
github.com/threefoldtech/rivine/modules/gateway.(*Gateway).Close(0xc00009c700, 0x0, 0x0)
	/Users/rob/workspace/go/src/github.com/threefoldtech/rivine/modules/gateway/gateway.go:186 +0x4e
github.com/threefoldtech/rivine/modules/gateway.TestThreadedHandleConn(0xc00016c100)
	/Users/rob/workspace/go/src/github.com/threefoldtech/rivine/modules/gateway/rpc_test.go:305 +0x4be
testing.tRunner(0xc00016c100, 0x1633ca8)
	/usr/local/go/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x652
```

**Comment by robvanmieghem** [comment]
> Might be in test `TestPruneNodeThreshold`, checking right now.
> 
> If you lower the timeout for the test to 5seconds, you can see it fails on this test.
> 
> `go test -v -race -tags='debug testing' -parallel=4 -timeout=5s ./modules/gateway`

on my laptop it succeds but takes a long time:
```

=== RUN   TestPruneNodeThreshold
--- PASS: TestPruneNodeThreshold (42.23s)

**Comment by robvanmieghem** [comment]
Goroutines dump of the stalled Test:
[StalledTestRoutines.txt](https://github.com/threefoldtech/rivine/files/4039554/StalledTestRoutines.txt)

**Comment by robvanmieghem** [comment]
Looks fixed https://travis-ci.org/threefoldtech/rivine/builds/634678252 , let's cross our fingers

**Comment by robvanmieghem** [comment]
Finally found the problem:
The gatewy close calls the threadgroup.Stop ( lock the bmumutex)which calls the peerTg.Stop that waits for all routines to finish
This includes threadedListenPeer that Adds a thread to the peerTg and defer Done's it.
It calls threadedHandleConn that tries to Add a thread to the gateway's main threadgroup but is unable to acquire the lock since  it is helt by the stopfunction.
